# Generated by Django 4.1.3 on 2025-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_processor_from_csv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='output_urls',
        ),
        migrations.AddField(
            model_name='productimage',
            name='output_image',
            field=models.ImageField(blank=True, null=True, upload_to='compressed_images/'),
        ),
    ]
